name = "serverless-qrcode-hub"
main = "index.js"
compatibility_date = "2025-03-15"

kv_namespaces = [
    # 注意：将下面的 id 替换为你自己拷贝的 KV 命名空间 id 才能正常使用！
    { binding = "KV_BINDING", id = "1861b1f17ac346e9aca647e7d4a4c143" },
]

[env.dev]
kv_namespaces = [
    { binding = "KV_BINDING", id = "91e94fe4c85d4e21a7f9898d97587e0e" },
]

[env.dev.triggers]
crons = ["*/10 * * * * *"]

[triggers]
crons = ["0 2 */1 * *"]

[assets]
directory = "./dist"
binding = "ASSETS"

[observability.logs]
enabled = true
